
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_actions_fields` DISABLE KEYS */;
REPLACE INTO `modx_actions_fields` VALUES (1601,'resource/create','modx-resource-access-permissions','tab','','modx-panel-resource','',9);
REPLACE INTO `modx_actions_fields` VALUES (1600,'resource/create','modx-panel-resource-tv','tab','','modx-panel-resource','tv',8);
REPLACE INTO `modx_actions_fields` VALUES (1598,'resource/create','syncsite','field','modx-page-settings-right-box-right','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1599,'resource/create','deleted','field','modx-page-settings-right-box-right','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1597,'resource/create','cacheable','field','modx-page-settings-right-box-right','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1596,'resource/create','modx-page-settings-right-box-right','tab','','modx-panel-resource','',7);
REPLACE INTO `modx_actions_fields` VALUES (1595,'resource/create','uri','field','modx-page-settings-right-box-left','modx-panel-resource','',5);
REPLACE INTO `modx_actions_fields` VALUES (1589,'resource/create','modx-page-settings-right-box-left','tab','','modx-panel-resource','',6);
REPLACE INTO `modx_actions_fields` VALUES (1590,'resource/create','isfolder','field','modx-page-settings-right-box-left','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1591,'resource/create','searchable','field','modx-page-settings-right-box-left','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1592,'resource/create','alias_visible','field','modx-page-settings-right-box-left','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1593,'resource/create','richtext','field','modx-page-settings-right-box-left','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1594,'resource/create','uri_override','field','modx-page-settings-right-box-left','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1586,'resource/create','publishedon','field','modx-page-settings-right','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1588,'resource/create','unpub_date','field','modx-page-settings-right','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1587,'resource/create','pub_date','field','modx-page-settings-right','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1584,'resource/create','menuindex','field','modx-page-settings-left','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1585,'resource/create','modx-page-settings-right','tab','','modx-panel-resource','',5);
REPLACE INTO `modx_actions_fields` VALUES (1583,'resource/create','content_dispo','field','modx-page-settings-left','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1582,'resource/create','content_type','field','modx-page-settings-left','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1581,'resource/create','class_key','field','modx-page-settings-left','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1580,'resource/create','parent-cmb','field','modx-page-settings-left','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1579,'resource/create','modx-page-settings-left','tab','','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1578,'resource/create','modx-page-settings','tab','','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1577,'resource/create','published','field','modx-resource-main-right','modx-panel-resource','',5);
REPLACE INTO `modx_actions_fields` VALUES (1575,'resource/create','link_attributes','field','modx-resource-main-right','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1576,'resource/create','hidemenu','field','modx-resource-main-right','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1574,'resource/create','menutitle','field','modx-resource-main-right','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1573,'resource/create','alias','field','modx-resource-main-right','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1572,'resource/create','template','field','modx-resource-main-right','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1571,'resource/create','modx-resource-main-right','tab','','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1570,'resource/create','introtext','field','modx-resource-main-left','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1569,'resource/create','description','field','modx-resource-main-left','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1568,'resource/create','longtitle','field','modx-resource-main-left','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1567,'resource/create','pagetitle','field','modx-resource-main-left','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1566,'resource/create','id','field','modx-resource-main-left','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1565,'resource/create','modx-resource-main-left','tab','','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1564,'resource/create','modx-resource-settings','tab','','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1563,'resource/update','modx-weblink-content','field','modx-resource-content','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1554,'resource/update','uri','field','modx-page-settings-right-box-left','modx-panel-resource','',5);
REPLACE INTO `modx_actions_fields` VALUES (1555,'resource/update','modx-page-settings-right-box-right','tab','','modx-panel-resource','',7);
REPLACE INTO `modx_actions_fields` VALUES (1556,'resource/update','cacheable','field','modx-page-settings-right-box-right','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1557,'resource/update','syncsite','field','modx-page-settings-right-box-right','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1558,'resource/update','deleted','field','modx-page-settings-right-box-right','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1559,'resource/update','modx-panel-resource-tv','tab','','modx-panel-resource','tv',8);
REPLACE INTO `modx_actions_fields` VALUES (1560,'resource/update','modx-resource-access-permissions','tab','','modx-panel-resource','',9);
REPLACE INTO `modx_actions_fields` VALUES (1561,'resource/update','modx-resource-content','field','modx-resource-content','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1562,'resource/update','modx-symlink-content','field','modx-resource-content','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1551,'resource/update','alias_visible','field','modx-page-settings-right-box-left','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1552,'resource/update','richtext','field','modx-page-settings-right-box-left','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1553,'resource/update','uri_override','field','modx-page-settings-right-box-left','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1550,'resource/update','searchable','field','modx-page-settings-right-box-left','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1549,'resource/update','isfolder','field','modx-page-settings-right-box-left','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1548,'resource/update','modx-page-settings-right-box-left','tab','','modx-panel-resource','',6);
REPLACE INTO `modx_actions_fields` VALUES (1546,'resource/update','pub_date','field','modx-page-settings-right','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1547,'resource/update','unpub_date','field','modx-page-settings-right','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1545,'resource/update','publishedon','field','modx-page-settings-right','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1542,'resource/update','content_dispo','field','modx-page-settings-left','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1543,'resource/update','menuindex','field','modx-page-settings-left','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1544,'resource/update','modx-page-settings-right','tab','','modx-panel-resource','',5);
REPLACE INTO `modx_actions_fields` VALUES (1541,'resource/update','content_type','field','modx-page-settings-left','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1540,'resource/update','class_key','field','modx-page-settings-left','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1537,'resource/update','modx-page-settings','tab','','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1538,'resource/update','modx-page-settings-left','tab','','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1539,'resource/update','parent-cmb','field','modx-page-settings-left','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1529,'resource/update','introtext','field','modx-resource-main-left','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1530,'resource/update','modx-resource-main-right','tab','','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1531,'resource/update','template','field','modx-resource-main-right','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1532,'resource/update','alias','field','modx-resource-main-right','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1533,'resource/update','menutitle','field','modx-resource-main-right','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1534,'resource/update','link_attributes','field','modx-resource-main-right','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1535,'resource/update','hidemenu','field','modx-resource-main-right','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1536,'resource/update','published','field','modx-resource-main-right','modx-panel-resource','',5);
REPLACE INTO `modx_actions_fields` VALUES (1525,'resource/update','id','field','modx-resource-main-left','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1526,'resource/update','pagetitle','field','modx-resource-main-left','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1527,'resource/update','longtitle','field','modx-resource-main-left','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1528,'resource/update','description','field','modx-resource-main-left','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1524,'resource/update','modx-resource-main-left','tab','','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1523,'resource/update','modx-resource-settings','tab','','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1602,'resource/create','modx-resource-content','field','modx-resource-content','modx-panel-resource','',0);
/*!40000 ALTER TABLE `modx_actions_fields` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

