
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_access_context` DISABLE KEYS */;
REPLACE INTO `modx_access_context` VALUES (1,'web','modUserGroup',0,9999,3);
REPLACE INTO `modx_access_context` VALUES (2,'mgr','modUserGroup',1,0,2);
REPLACE INTO `modx_access_context` VALUES (3,'web','modUserGroup',1,0,2);
REPLACE INTO `modx_access_context` VALUES (4,'web','modUserGroup',2,9999,12);
REPLACE INTO `modx_access_context` VALUES (5,'mgr','modUserGroup',2,9999,12);
REPLACE INTO `modx_access_context` VALUES (6,'web','modUserGroup',3,9999,13);
REPLACE INTO `modx_access_context` VALUES (7,'mgr','modUserGroup',3,9999,13);
REPLACE INTO `modx_access_context` VALUES (8,'mgr','modUserGroup',1,9999,14);
REPLACE INTO `modx_access_context` VALUES (9,'mgr','modUserGroup',1,9999,15);
REPLACE INTO `modx_access_context` VALUES (10,'mgr','modUserGroup',1,9999,16);
REPLACE INTO `modx_access_context` VALUES (11,'mgr','modUserGroup',1,9999,17);
/*!40000 ALTER TABLE `modx_access_context` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

