
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_system_eventnames` DISABLE KEYS */;
REPLACE INTO `modx_system_eventnames` VALUES ('OnPluginEventBeforeSave',1,'Plugin Events');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPluginEventSave',1,'Plugin Events');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPluginEventBeforeRemove',1,'Plugin Events');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPluginEventRemove',1,'Plugin Events');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceGroupSave',1,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceGroupBeforeSave',1,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceGroupRemove',1,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceGroupBeforeRemove',1,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnSnippetBeforeSave',1,'Snippets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnSnippetSave',1,'Snippets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnSnippetBeforeRemove',1,'Snippets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnSnippetRemove',1,'Snippets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnSnipFormPrerender',1,'Snippets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnSnipFormRender',1,'Snippets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeSnipFormSave',1,'Snippets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnSnipFormSave',1,'Snippets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeSnipFormDelete',1,'Snippets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnSnipFormDelete',1,'Snippets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTemplateBeforeSave',1,'Templates');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTemplateSave',1,'Templates');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTemplateBeforeRemove',1,'Templates');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTemplateRemove',1,'Templates');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTempFormPrerender',1,'Templates');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTempFormRender',1,'Templates');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeTempFormSave',1,'Templates');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTempFormSave',1,'Templates');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeTempFormDelete',1,'Templates');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTempFormDelete',1,'Templates');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTemplateVarBeforeSave',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTemplateVarSave',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTemplateVarBeforeRemove',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTemplateVarRemove',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTVFormPrerender',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTVFormRender',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeTVFormSave',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTVFormSave',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeTVFormDelete',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTVFormDelete',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTVInputRenderList',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTVInputPropertiesList',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTVOutputRenderList',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnTVOutputRenderPropertiesList',1,'Template Variables');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserGroupBeforeSave',1,'User Groups');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserGroupSave',1,'User Groups');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserGroupBeforeRemove',1,'User Groups');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserGroupRemove',1,'User Groups');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeUserGroupFormSave',1,'User Groups');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserGroupFormSave',1,'User Groups');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeUserGroupFormRemove',1,'User Groups');
REPLACE INTO `modx_system_eventnames` VALUES ('OnDocFormPrerender',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnDocFormRender',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeDocFormSave',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnDocFormSave',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeDocFormDelete',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnDocFormDelete',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnDocPublished',5,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnDocUnPublished',5,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeEmptyTrash',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnEmptyTrash',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceTVFormPrerender',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceTVFormRender',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceDelete',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceUndelete',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceBeforeSort',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceSort',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceDuplicate',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceToolbarLoad',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceRemoveFromResourceGroup',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceAddToResourceGroup',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnRichTextEditorRegister',1,'RichText Editor');
REPLACE INTO `modx_system_eventnames` VALUES ('OnRichTextEditorInit',1,'RichText Editor');
REPLACE INTO `modx_system_eventnames` VALUES ('OnRichTextBrowserInit',1,'RichText Editor');
REPLACE INTO `modx_system_eventnames` VALUES ('OnWebLogin',3,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeWebLogout',3,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnWebLogout',3,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnManagerLogin',2,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeManagerLogout',2,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnManagerLogout',2,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeWebLogin',3,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnWebAuthentication',3,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeManagerLogin',2,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnManagerAuthentication',2,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnManagerLoginFormRender',2,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnManagerLoginFormPrerender',2,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPageUnauthorized',1,'Security');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserFormPrerender',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserFormRender',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeUserFormSave',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserFormSave',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeUserFormDelete',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserFormDelete',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserNotFound',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeUserActivate',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserActivate',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeUserDeactivate',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserDeactivate',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeUserDuplicate',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserDuplicate',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserChangePassword',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserBeforeRemove',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserBeforeSave',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserSave',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserRemove',1,'Users');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserBeforeAddToGroup',1,'User Groups');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserAddToGroup',1,'User Groups');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserBeforeRemoveFromGroup',1,'User Groups');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserRemoveFromGroup',1,'User Groups');
REPLACE INTO `modx_system_eventnames` VALUES ('OnWebPagePrerender',5,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeCacheUpdate',4,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnCacheUpdate',4,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnLoadWebPageCache',4,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeSaveWebPageCache',4,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnSiteRefresh',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnFileManagerUpload',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnFileCreateFormPrerender',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnFileEditFormPrerender',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnManagerPageInit',2,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnManagerPageBeforeRender',2,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnManagerPageAfterRender',2,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnWebPageInit',5,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnLoadWebDocument',5,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnParseDocument',5,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnWebPageComplete',5,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeManagerPageInit',2,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPageNotFound',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnHandleRequest',5,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnSiteSettingsRender',1,'Settings');
REPLACE INTO `modx_system_eventnames` VALUES ('OnInitCulture',1,'Internationalization');
REPLACE INTO `modx_system_eventnames` VALUES ('OnCategorySave',1,'Categories');
REPLACE INTO `modx_system_eventnames` VALUES ('OnCategoryBeforeSave',1,'Categories');
REPLACE INTO `modx_system_eventnames` VALUES ('OnCategoryRemove',1,'Categories');
REPLACE INTO `modx_system_eventnames` VALUES ('OnCategoryBeforeRemove',1,'Categories');
REPLACE INTO `modx_system_eventnames` VALUES ('OnChunkSave',1,'Chunks');
REPLACE INTO `modx_system_eventnames` VALUES ('OnChunkBeforeSave',1,'Chunks');
REPLACE INTO `modx_system_eventnames` VALUES ('OnChunkRemove',1,'Chunks');
REPLACE INTO `modx_system_eventnames` VALUES ('OnChunkBeforeRemove',1,'Chunks');
REPLACE INTO `modx_system_eventnames` VALUES ('OnChunkFormPrerender',1,'Chunks');
REPLACE INTO `modx_system_eventnames` VALUES ('OnChunkFormRender',1,'Chunks');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeChunkFormSave',1,'Chunks');
REPLACE INTO `modx_system_eventnames` VALUES ('OnChunkFormSave',1,'Chunks');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeChunkFormDelete',1,'Chunks');
REPLACE INTO `modx_system_eventnames` VALUES ('OnChunkFormDelete',1,'Chunks');
REPLACE INTO `modx_system_eventnames` VALUES ('OnContextSave',1,'Contexts');
REPLACE INTO `modx_system_eventnames` VALUES ('OnContextBeforeSave',1,'Contexts');
REPLACE INTO `modx_system_eventnames` VALUES ('OnContextRemove',1,'Contexts');
REPLACE INTO `modx_system_eventnames` VALUES ('OnContextBeforeRemove',1,'Contexts');
REPLACE INTO `modx_system_eventnames` VALUES ('OnContextFormPrerender',2,'Contexts');
REPLACE INTO `modx_system_eventnames` VALUES ('OnContextFormRender',2,'Contexts');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPluginSave',1,'Plugins');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPluginBeforeSave',1,'Plugins');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPluginRemove',1,'Plugins');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPluginBeforeRemove',1,'Plugins');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPluginFormPrerender',1,'Plugins');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPluginFormRender',1,'Plugins');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforePluginFormSave',1,'Plugins');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPluginFormSave',1,'Plugins');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforePluginFormDelete',1,'Plugins');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPluginFormDelete',1,'Plugins');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPropertySetSave',1,'Property Sets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPropertySetBeforeSave',1,'Property Sets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPropertySetRemove',1,'Property Sets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPropertySetBeforeRemove',1,'Property Sets');
REPLACE INTO `modx_system_eventnames` VALUES ('OnMediaSourceBeforeFormDelete',1,'Media Sources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnMediaSourceBeforeFormSave',1,'Media Sources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnMediaSourceGetProperties',1,'Media Sources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnMediaSourceFormDelete',1,'Media Sources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnMediaSourceFormSave',1,'Media Sources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnMediaSourceDuplicate',1,'Media Sources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnElementNotFound',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceAutoPublish',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnFileManagerDirCreate',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnFileManagerDirRemove',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnFileManagerDirRename',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnFileManagerFileRename',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnFileManagerFileRemove',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnFileManagerFileUpdate',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnFileManagerFileCreate',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnFileManagerBeforeUpload',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnFileManagerMoveObject',1,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnMODXInit',5,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserProfileBeforeSave',1,'User Profiles');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserProfileSave',1,'User Profiles');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserProfileBeforeRemove',1,'User Profiles');
REPLACE INTO `modx_system_eventnames` VALUES ('OnUserProfileRemove',1,'User Profiles');
REPLACE INTO `modx_system_eventnames` VALUES ('OnResourceCacheUpdate',1,'Resources');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPackageInstall',2,'Package Manager');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPackageUninstall',2,'Package Manager');
REPLACE INTO `modx_system_eventnames` VALUES ('OnPackageRemove',2,'Package Manager');
REPLACE INTO `modx_system_eventnames` VALUES ('OnBeforeRegisterClientScripts',5,'System');
REPLACE INTO `modx_system_eventnames` VALUES ('pdoToolsOnFenomInit',6,'pdoTools');
/*!40000 ALTER TABLE `modx_system_eventnames` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

