
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_actions` DISABLE KEYS */;
REPLACE INTO `modx_actions` VALUES (1,'core','welcome',1,'welcome,configcheck','','');
REPLACE INTO `modx_actions` VALUES (2,'core','system',0,'','','');
REPLACE INTO `modx_actions` VALUES (3,'core','browser',0,'file','','');
REPLACE INTO `modx_actions` VALUES (4,'core','context/create',1,'context,setting,access,policy,user','','Contexts');
REPLACE INTO `modx_actions` VALUES (5,'core','context/update',1,'context,setting,access,policy,user','','Contexts');
REPLACE INTO `modx_actions` VALUES (6,'core','context/view',1,'context','','Contexts');
REPLACE INTO `modx_actions` VALUES (7,'core','element',1,'element','','');
REPLACE INTO `modx_actions` VALUES (8,'core','element/chunk',1,'chunk,category,propertyset,element','','Chunks');
REPLACE INTO `modx_actions` VALUES (9,'core','element/chunk/create',1,'chunk,category,propertyset,element','','Chunks');
REPLACE INTO `modx_actions` VALUES (10,'core','element/chunk/update',1,'chunk,category,propertyset,element','','Chunks');
REPLACE INTO `modx_actions` VALUES (11,'core','element/plugin',1,'plugin,category,system_events,propertyset,element','','Plugins');
REPLACE INTO `modx_actions` VALUES (12,'core','element/plugin/create',1,'plugin,category,system_events,propertyset,element','','Plugins');
REPLACE INTO `modx_actions` VALUES (13,'core','element/plugin/update',1,'plugin,category,system_events,propertyset,element','','Plugins');
REPLACE INTO `modx_actions` VALUES (14,'core','element/snippet',1,'snippet,propertyset,element','','Snippets');
REPLACE INTO `modx_actions` VALUES (15,'core','element/snippet/create',1,'snippet,propertyset,element','','Snippets');
REPLACE INTO `modx_actions` VALUES (16,'core','element/snippet/update',1,'snippet,propertyset,element','','Snippets');
REPLACE INTO `modx_actions` VALUES (17,'core','element/template',1,'template,propertyset,element','','Templates');
REPLACE INTO `modx_actions` VALUES (18,'core','element/template/create',1,'template,propertyset,element','','Templates');
REPLACE INTO `modx_actions` VALUES (19,'core','element/template/update',1,'template,propertyset,element','','Templates');
REPLACE INTO `modx_actions` VALUES (20,'core','element/template/tvsort',1,'template,tv,propertyset,element','','');
REPLACE INTO `modx_actions` VALUES (21,'core','element/tv',1,'tv,propertyset,element','','Template+Variables');
REPLACE INTO `modx_actions` VALUES (22,'core','element/tv/create',1,'tv,tv_widget,propertyset,element','','Template+Variables');
REPLACE INTO `modx_actions` VALUES (23,'core','element/tv/update',1,'tv,tv_widget,propertyset,element','','Template+Variables');
REPLACE INTO `modx_actions` VALUES (24,'core','element/view',1,'element','','');
REPLACE INTO `modx_actions` VALUES (25,'core','resource',1,'','','');
REPLACE INTO `modx_actions` VALUES (26,'core','security/usergroup/create',1,'user,access,policy,context','','User+Groups');
REPLACE INTO `modx_actions` VALUES (27,'core','security/usergroup/update',1,'user,access,policy,context','','User+Groups');
REPLACE INTO `modx_actions` VALUES (28,'core','resource/data',1,'resource','','Resource');
REPLACE INTO `modx_actions` VALUES (29,'core','resource/empty_recycle_bin',1,'resource','','');
REPLACE INTO `modx_actions` VALUES (30,'core','resource/update',1,'resource','','Resource');
REPLACE INTO `modx_actions` VALUES (31,'core','security',1,'user','','');
REPLACE INTO `modx_actions` VALUES (32,'core','security/role',1,'user','','Roles');
REPLACE INTO `modx_actions` VALUES (33,'core','security/user/create',1,'user,setting,access','','Users');
REPLACE INTO `modx_actions` VALUES (34,'core','security/user/update',1,'user,setting,access','','Users');
REPLACE INTO `modx_actions` VALUES (35,'core','security/login',1,'login','','');
REPLACE INTO `modx_actions` VALUES (36,'core','system/refresh_site',1,'','','');
REPLACE INTO `modx_actions` VALUES (37,'core','system/phpinfo',1,'','','');
REPLACE INTO `modx_actions` VALUES (38,'core','resource/tvs',0,'','','');
REPLACE INTO `modx_actions` VALUES (39,'core','system/file',1,'file','','');
REPLACE INTO `modx_actions` VALUES (40,'core','system/file/edit',1,'file','','');
REPLACE INTO `modx_actions` VALUES (41,'core','security/access/policy/update',1,'user,policy','','Policies');
REPLACE INTO `modx_actions` VALUES (42,'core','workspaces/package/view',1,'workspace,namespace','','Package+Management');
REPLACE INTO `modx_actions` VALUES (43,'core','security/access/policy/template/update',1,'user,policy','','PolicyTemplates');
REPLACE INTO `modx_actions` VALUES (44,'core','security/forms/profile/update',1,'formcustomization,user,access,policy','','Form+Customization+Profiles');
REPLACE INTO `modx_actions` VALUES (45,'core','security/forms/set/update',1,'formcustomization,user,access,policy','','Form+Customization+Sets');
REPLACE INTO `modx_actions` VALUES (46,'core','system/dashboards/update',1,'dashboards,user','','Dashboards');
REPLACE INTO `modx_actions` VALUES (47,'core','system/dashboards/create',1,'dashboards,user','','Dashboards');
REPLACE INTO `modx_actions` VALUES (48,'core','system/dashboards/widget/update',1,'dashboards,user','','Dashboard+Widgets');
REPLACE INTO `modx_actions` VALUES (49,'core','system/dashboards/widget/create',1,'dashboards,user','','Dashboard+Widgets');
REPLACE INTO `modx_actions` VALUES (50,'core','source/create',1,'sources,namespace','','Media+Sources');
REPLACE INTO `modx_actions` VALUES (51,'core','source/update',1,'sources,namespace','','Media+Sources');
REPLACE INTO `modx_actions` VALUES (52,'core','system/file/create',1,'file','','');
REPLACE INTO `modx_actions` VALUES (53,'core','system/dashboards',1,'about','','Dashboards');
REPLACE INTO `modx_actions` VALUES (54,'core','search',1,'','','');
REPLACE INTO `modx_actions` VALUES (55,'core','resource/create',1,'resource','','Resource');
REPLACE INTO `modx_actions` VALUES (56,'core','security/user',1,'user','','Users');
REPLACE INTO `modx_actions` VALUES (57,'core','security/permission',1,'user,access,policy','','Security');
REPLACE INTO `modx_actions` VALUES (58,'core','security/resourcegroup/index',1,'resource,user,access','','Resource+Groups');
REPLACE INTO `modx_actions` VALUES (59,'core','security/forms',1,'formcustomization,user,access,policy','','Customizing+The+Manager');
REPLACE INTO `modx_actions` VALUES (60,'core','system/import',1,'import','','');
REPLACE INTO `modx_actions` VALUES (61,'core','system/import/html',1,'import','','');
REPLACE INTO `modx_actions` VALUES (62,'core','element/propertyset/index',1,'element,category,propertyset','','Properties+and+Property+Sets');
REPLACE INTO `modx_actions` VALUES (63,'core','source/index',1,'sources,namespace','','Media+Sources');
REPLACE INTO `modx_actions` VALUES (64,'core','resource/site_schedule',1,'resource','','');
REPLACE INTO `modx_actions` VALUES (65,'core','system/logs/index',1,'manager_log','','');
REPLACE INTO `modx_actions` VALUES (66,'core','system/event',1,'system_events','','');
REPLACE INTO `modx_actions` VALUES (67,'core','system/info',1,'system_info','','');
REPLACE INTO `modx_actions` VALUES (68,'core','help',1,'about','','');
REPLACE INTO `modx_actions` VALUES (69,'core','workspaces',1,'workspace','','Package+Management');
REPLACE INTO `modx_actions` VALUES (70,'core','system/settings',1,'setting','','Settings');
REPLACE INTO `modx_actions` VALUES (71,'core','workspaces/lexicon',1,'package_builder,lexicon,namespace','','Internationalization');
REPLACE INTO `modx_actions` VALUES (72,'core','system/contenttype',1,'content_type','','Content+Types');
REPLACE INTO `modx_actions` VALUES (73,'core','context',1,'context','','Contexts');
REPLACE INTO `modx_actions` VALUES (74,'core','system/action',1,'action,menu,namespace','','Actions+and+Menus');
REPLACE INTO `modx_actions` VALUES (75,'core','workspaces/namespace',1,'workspace,package_builder,lexicon,namespace','','Namespaces');
REPLACE INTO `modx_actions` VALUES (76,'core','security/profile',1,'user','','');
REPLACE INTO `modx_actions` VALUES (77,'core','security/message',1,'messages','','');
REPLACE INTO `modx_actions` VALUES (85,'formit','index',1,'formit:mgr','','');
/*!40000 ALTER TABLE `modx_actions` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

